version: "3"
services:
  jenkins:
    image: mark59/jenkins-ci
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ".:/var/mark59"
      - "~/apache-jmeter:/var/apache-jmeter"
      - "~/Mark59_Runs:/var/Mark59_Runs"
  datahunter:
    image: mark59/datahunter
    expose:
      - "8081"
    ports:
      - "8081:8081"
    volumes:
      - ".:/var/mark59"
  mark59servermetricsweb:
    image: mark59/mark59-server-metrics-web
    expose:
      - "8085"
    ports:
      - "8085:8085"
    volumes:
      - ".:/var/mark59"

